[general]
library_name = "libclangex"
output_file_path = "../src/clang/LibClangEx.jl"
module_name = "LibClangEx"
export_symbol_prefixes = ["clang", "CX"]
prologue_file_path = "./prologue.jl"

use_deterministic_symbol = true
use_julia_native_enum_type = true