# Generated from deps/ClangExtra/include/clang-ex/AST/TypeNodes.inc by gen/type_nodes.jl — do not edit.
# CXTypeClass -> concrete carrier; classes without a wrapped `<name>Type`
# carrier are absent, so resolve falls back to UnexposedType.
const TYPE_CLASS_TO_TYPE = Dict{CXTypeClass,Any}(
    LibClangEx.CXTypeClass_Adjusted => AdjustedType,
    LibClangEx.CXTypeClass_Decayed => DecayedType,
    LibClangEx.CXTypeClass_ConstantArray => ConstantArrayType,
    LibClangEx.CXTypeClass_DependentSizedArray => DependentSizedArrayType,
    LibClangEx.CXTypeClass_IncompleteArray => IncompleteArrayType,
    LibClangEx.CXTypeClass_VariableArray => VariableArrayType,
    LibClangEx.CXTypeClass_Atomic => AtomicType,
    LibClangEx.CXTypeClass_Builtin => BuiltinType,
    LibClangEx.CXTypeClass_Complex => ComplexType,
    LibClangEx.CXTypeClass_Decltype => DecltypeType,
    LibClangEx.CXTypeClass_DeducedTemplateSpecialization => DeducedTemplateSpecializationType,
    LibClangEx.CXTypeClass_DependentAddressSpace => DependentAddressSpaceType,
    LibClangEx.CXTypeClass_DependentName => DependentNameType,
    LibClangEx.CXTypeClass_DependentSizedExtVector => DependentSizedExtVectorType,
    LibClangEx.CXTypeClass_DependentTemplateSpecialization => DependentTemplateSpecializationType,
    LibClangEx.CXTypeClass_Elaborated => ElaboratedType,
    LibClangEx.CXTypeClass_FunctionNoProto => FunctionNoProtoType,
    LibClangEx.CXTypeClass_FunctionProto => FunctionProtoType,
    LibClangEx.CXTypeClass_InjectedClassName => InjectedClassNameType,
    LibClangEx.CXTypeClass_MacroQualified => MacroQualifiedType,
    LibClangEx.CXTypeClass_MemberPointer => MemberPointerType,
    LibClangEx.CXTypeClass_Paren => ParenType,
    LibClangEx.CXTypeClass_Pointer => PointerType,
    LibClangEx.CXTypeClass_LValueReference => LValueReferenceType,
    LibClangEx.CXTypeClass_RValueReference => RValueReferenceType,
    LibClangEx.CXTypeClass_SubstTemplateTypeParmPack => SubstTemplateTypeParmPackType,
    LibClangEx.CXTypeClass_SubstTemplateTypeParm => SubstTemplateTypeParmType,
    LibClangEx.CXTypeClass_Enum => EnumType,
    LibClangEx.CXTypeClass_Record => RecordType,
    LibClangEx.CXTypeClass_TemplateSpecialization => TemplateSpecializationType,
    LibClangEx.CXTypeClass_TemplateTypeParm => TemplateTypeParmType,
    LibClangEx.CXTypeClass_Typedef => TypedefType,
    LibClangEx.CXTypeClass_UnaryTransform => UnaryTransformType,
    LibClangEx.CXTypeClass_UnresolvedUsing => UnresolvedUsingType,
    LibClangEx.CXTypeClass_Using => UsingType,
)
